variables:
    AUDIT_AWS_INSPECTOR_ALERT_LIST:
        required: false
        type: array
        default:
            - inspector-findings # 
            - ec2-inventory # 
        description: "Which rules would you like to run? Possible values are inspector-findings ec2-inventory"
